sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 114514
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t9XAUjCgTtvKK3UWEy6
    access-key-secret: 548NMpCQ5G4v3W7YAlTW24NtDf28Pz
    bucket-name: zhenxun233
  redis:
    host: localhost
    port: 6379
    password: 114514
    database: 10
  wechat:
    appid: wxc71632812d6e4c62
    secret: 4e4f7543b523540c70014cf2a1bb1438